---
- name: "Install LAMP stack in Amazon Linux"
  hosts: all
  become: true
  vars_files:
    - lampstack.vars

  tasks:
    - name: "Update Cache in Amazon Linux"
      when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
      yum:
        name: "*"
        state: present
      tags:
        - lamp

    - name : "Installing Packages in Amazon Linux"
      when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
      yum:
        name: "{{ web_packages }}"
        state: present
      tags:
        - apache

    - name: "Install PHP in Amazon Linux"
      when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
      shell: amazon-linux-extras install php7.4 -y
      tags:
        - php

    - name: "Creating httpd configuration file in Amazon Linux"
      when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
      template:
        src: ./httpd.conf
        dest: /etc/httpd/conf/httpd.conf
      register: conf_status
      tags:
        - apache

    - name: "Restart httpd service in Amazon Linux"
      when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon" and conf_status.changed == true
      service:
        name: "{{item}}"
        state: restarted
      with_items:
        - httpd
        - php-fpm
      tags:
        - apache
        - php

    - name: "Create virtual config Directory in Amazon Linux"
      when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
      file:
        path: /var/www/html/{{domain_name}}
        state: directory
        owner: "{{httpd_user}}"
        group: "{{httpd_user}}"
      tags:
        - apache

